### ISSUE TITLE
Binary for MacOS? 

### ISSUE THREAD

**Issue by sksq96** [ravenscroftj/turbopilot#10]
Is there a compiled binary for MacOS? Will this be supported on M1 Apple Silicon? Thanks!

**Comment by sksq96** [comment]
[MacOS M1 Binary](https://github.com/ravenscroftj/turbopilot/files/11231879/macos.bin.zip) for anyone looking to not build and work directly.

**Comment by ravenscroftj** [comment]
Thanks! I need to work out how to get github actions to build a mac arm binary as part of the release process
