### ISSUE TITLE
error with today's new PR

### ISSUE THREAD

**Issue by czkoko** [ravenscroftj/turbopilot#19]
I just updated the latest submission code, compiled it again, and then something went wrong.
error:  `ggml_new_tensor_impl: not enough space in the context's memory pool (needed 322235776, available 268435456)`

M1 macos 13.2

Releases v0.0.4 Work normally

**Comment by ravenscroftj** [comment]
Hey

What version of the model are you trying to use? Does it crash after you submit a prompt? If so, how big is the prompt?

Thanks

**Comment by czkoko** [comment]
I tested codegen-2B, codegen-350m, and there was a problem with both models.
The model can be loaded successfully, but once it is receive a prompt, an error will be show.
the prompt very small, just like "func hello()"

**Comment by ravenscroftj** [comment]
Are you building with OpenBLAS or Apple Accelerate enabled by any chance

**Comment by czkoko** [comment]
just cmake . and make
There is no problem with the program I compiled the code a few days ago.

**Comment by ravenscroftj** [comment]
Ok thanks - try now with commit [bcf24e6](https://github.com/ravenscroftj/turbopilot/commit/bcf24e673912adc833c249ae63b3f4e63d1cca3d) - I think I have identified an issue with the batch size setting which I changed today to enable BLAS. It seems to cause the memory issue for me on my laptop too.

**Comment by czkoko** [comment]
thank you, It is working normally now.

**Comment by ravenscroftj** [comment]
great and now I know what is wrong - hopefully I can fix memory allocation AND bring a performance boost
