### ISSUE TITLE
Support Windows Builds

### ISSUE THREAD

**Issue by ravenscroftj** [ravenscroftj/turbopilot#24]
Llama.cpp provides windows build support but currently turbopilot does not. A few people have been caught out by this (#17) - I would like to implement windows builds out of the box.

In order to make this work a new job needs to be added to the githhub action that builds codeserve which runs on windows and uploads the .exe artifact (the logic should be pretty much the same as the other builds). It may be necessary to copy workarounds for any windows specific quirks from llama.cpp

**Comment by JohnClaw** [comment]
I wait for Windows version. Will it run on 16gb ram?

**Comment by notBradPitt** [comment]
Looking forward to this

**Comment by ravenscroftj** [comment]
Windows binaries now available in the v0.0.5 release
