### ISSUE TITLE
Not getting any predictions - but posting to turbopilot..........

### ISSUE THREAD

**Issue by voarsh2** [ravenscroftj/turbopilot#7]
Running the latest code for turbopilot. Running the extension (fauxpilot) v1.1.4. I've tried earlier versions too...

It runs:
![image](https://user-images.githubusercontent.com/60437695/231631586-3559ca63-daf1-4036-9bae-a37702a6dcd0.png)

I see POST requests:
![image](https://user-images.githubusercontent.com/60437695/231631680-d364f2e5-5417-4032-9296-f42824e9f958.png)

I see the calls in VSC:
![image](https://user-images.githubusercontent.com/60437695/231631788-ae6fd933-b916-441b-b152-7a47c7c2ac9b.png)

But I don't get any prediction as per the project's .gif image.... 🗡️ 
Am I missing something?

My settings:
![image](https://user-images.githubusercontent.com/60437695/231631943-5767acd2-392d-4769-835b-0f735797cfb0.png)

![image](https://user-images.githubusercontent.com/60437695/231631997-bbb3cf0f-a713-4b32-a84a-5135b3b88a21.png)

**Comment by ravenscroftj** [comment]
Thanks for your ticket. Looking at the prediction logs you screenshotted there it's taking about 2 minutes to generate a response on your system - I'm not 100% sure but its possible you're hitting a timeout issue from within vscode. Are you seeing any timeout logs from fauxcode? What system are you running on and how many threads are you using?

**Comment by voarsh2** [comment]
> What system are you running on and how many threads are you using?

The memory usage was around 4GB's. 12 x AMD Ryzen 5 3600X 6-Core Processor (1 Socket) (with AVX2 support).


At the time I believe I was using 6 threads. I had also been using the 2B model.

>  I'm not 100% sure but its possible you're hitting a timeout issue from within vscode. Are you seeing any timeout logs from fauxcode?

The developer tools shows the extension requests with making the requests to the server and also shows the request is done, but no prediction is returned. There's no log there about a timeout that I can see. :/ 

I tried with 2 threads and saw a prediction (once) - trying to reproduce... but it seems very hit and miss.

![image](https://user-images.githubusercontent.com/60437695/231782452-f58d70dc-225c-4232-9e81-fe07fbc43d83.png)

![image](https://user-images.githubusercontent.com/60437695/231783190-4f7b526a-8ca9-4be6-b291-c576c9887f1b.png)

**Comment by ravenscroftj** [comment]
Ok great thank you for your report - is it possible that k8s is trying to kill and restart the pod while prediction is happening and the health endpoint is timing out? I imagine k8s would be a pretty common deployment case so I definitely want to support a liveness check. I think the web server only only handle one request at a time at the moment - I will see if I can turn on Crow's multithreaded support.

I also noticed that the fauxpilot plugin can be a little bit fussy about retaining focus - I think if you start a prediction, change to another window and change back it will cancel the suggestion popup. I might dive into the plugin itself over the weekend to see if I can make any improvements myself - from a UX point of view even a notification of progress would be welcome right?

**Comment by ravenscroftj** [comment]
I've now enabled multi-threaded serving so hopefully you won't find that the healthcheck endpoint becomes unresponsive while the system is working. 

I've also forked the fauxpilot plugin for VSCode which actually shows a status wheel while it is thinking which helps with the UX a bit. I've provided a [custom build](https://github.com/ravenscroftj/vscode-fauxpilot/releases) of the plugin that can be downloaded and installed via the install from VSIX file option for now (hopefully the upstream maintainer will incorporate my PR).

![image](https://user-images.githubusercontent.com/47742/232225449-f06b0fd0-ee7a-4b1a-aa9e-b864b4df953e.png)

I've also noticed that the fauxcode plugin is a bit fussy about maintaining focus so if you click out of the window while it's thinking it seems to silently throw the suggestions away.

**Comment by ravenscroftj** [comment]
@whatvn I think that'd be great - I'm looking into the feasibility at the moment. Within VSCode we're limited by what their API lets us do. The [API Documentation](https://code.visualstudio.com/api/references/vscode-api#InlineCompletionItemProvider) states that "Providers are asked for completions either explicitly by a user gesture or implicitly when typing." so in theory it seems possible but I am looking at how to make it work with a user gesture or at least make it wait a little longer when you stop typing before sending a request
