### ISSUE TITLE
arm64 image 

### ISSUE THREAD

**Issue by GeekWorkCode** [ravenscroftj/turbopilot#8]
I have an arm64 server. Can I support arm64?

**Comment by ravenscroftj** [comment]
Hi there,

I need to add arm64 builds to the CI pipeline. In the mean time, you can try cloning the repo and subproject and running docker build from your server - it should pull in the arm dependencies. I will get something set up for automatic arm build soon

**Comment by GeekWorkCode** [comment]
I tried to compile the error myself
1、git clone https://github.com/ravenscroftj/turbopilot.git
2、cd turbopilot
3、docker build -t turbopilot:0.1 .
 => ERROR [build 6/7] RUN cmake -D CMAKE_EXE_LINKER_FLAGS="-static" ..                                                                                                                          0.2s
------
 > [build 6/7] RUN cmake -D CMAKE_EXE_LINKER_FLAGS="-static" ..:
#0 0.221 CMake Warning:
#0 0.221   Ignoring extra path from command line:
#0 0.221 
#0 0.221    ".."
#0 0.221 
#0 0.221 
#0 0.221 CMake Error: The source directory "/build/ggml" does not appear to contain CMakeLists.txt.
#0 0.221 Specify --help for usage, or press the help button on the CMake GUI.
------
Dockerfile:11
--------------------
   9 |     WORKDIR  /build/ggml/build
  10 |     
  11 | >>> RUN cmake -D CMAKE_EXE_LINKER_FLAGS="-static" ..
  12 |     RUN make codegen-serve
  13 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c cmake -D CMAKE_EXE_LINKER_FLAGS=\"-static\" .." did not complete successfully: exit code: 1

**Comment by ravenscroftj** [comment]
Hi again @GeekWorkCode 

I have now added ARM64 builds to the CI pipeline so you should just be able to run it straight away now:

```
docker run --rm -it \
  -v ./models:/models \
  -e THREADS=6 \
  -e MODEL="/models/codegen-2B-multi-ggml-4bit-quant.bin" \
  -p 18080:18080 \
  ghcr.io/ravenscroftj/turbopilot:latest
```

Please note the docker image URI name has **changed** to `ghcr.io/ravenscroftj/turbopilot:latest`
