### ISSUE TITLE
No binary 0.0.2 release 

### ISSUE THREAD

**Issue by whatvn** [ravenscroftj/turbopilot#9]
Can you check whether binary is updated in latest release? I cannot find it, thank!

**Comment by ravenscroftj** [comment]
hi whatvn - I have now got automated builds working and attached to releases going forwards so you should find a binary for v 0.0.3 [here](https://github.com/ravenscroftj/turbopilot/releases/tag/v0.0.3) - let me know if you want a binary specifically for v0.0.2 and can't build one yourself.
